### ISSUE TITLE
Only update share counts when number goes up

### ISSUE THREAD

**Issue by billerickson** [jaredatch/Shared-Counts#51]
Currently we update a post's share data with whatever is received from the API. This leads to the following issues:
- If API is down, exceeded quota, or has incorrect data for some reason, share counts go to zero.
- Pinterest shares fluctuate and some people get nervous when they see the Pinterest count go down

**Comment by jaredatch** [comment]
We need to ideally prioritize this for 1.4.

A few weeks ago there were a few days all Pinterest counts went to 0 from the Shared Count API due to latency issues with the Pinterest API. So all those counts were lost for a few days.

If anything ever happens to the SC API (either entirely or just certain counts like this instance), having this in place would prevent major damage until alternatives can be considered.

**Comment by billerickson** [comment]
@jaredatch Can you look this over when you get a chance and make sure it works as you expected? https://github.com/jaredatch/Shared-Counts/commit/d4d2fbe694aef753e0203a544b74152a9aa8de36
