### ISSUE TITLE
Icons showing shares when settings is None

### ISSUE THREAD

**Issue by JiveDig** [jaredatch/Shared-Counts#81]
Discussed with Bill already. I think i found the issue and will submit a PR in a min. Feel free to edit as needed.

Putting this here to reference the PR against.

**Comment by JiveDig** [comment]
![Screenshot 2019-05-24 15 26 59](https://user-images.githubusercontent.com/540990/58352030-62a8aa80-7e38-11e9-9efd-7f2b12323b2d.png)

![Screenshot 2019-05-24 15 27 28](https://user-images.githubusercontent.com/540990/58352058-72c08a00-7e38-11e9-93db-9236fc9bef9e.png)

**Comment by JiveDig** [comment]
Any chance of getting this merged/tested? Just about to launch the new theme (screenshot above) for them and hitting this on live.

**Comment by billerickson** [comment]
Sorry for the delay on this. 

I'm having trouble reproducing the error. When I select "None" as the count and "Fancy" as the style, I don't get any counts displayed.

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/330X3q3M3D0Z2A3D1T1D/Screen%20Shot%202019-09-15%20at%209.42.56%20AM.png?X-CloudApp-Visitor-Id=57dd62b2e547854fee104e672ecd4cfa&v=4f201a29)

There's no markup appearing for the count:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2O202k0d422X39292V3d/Screen%20Shot%202019-09-15%20at%209.44.30%20AM.png?X-CloudApp-Visitor-Id=57dd62b2e547854fee104e672ecd4cfa&v=a7d36137)

The logic for removing the count markup is [here](https://github.com/jaredatch/Shared-Counts/blob/develop/includes/class-shared-counts-front.php#L642-L648). It's a bit confusing because both of these options reference settings that are hidden if you have "None" as your count source.

I was able to replicate your screenshot with the following workflow: 
- Go to Settings > Shared Counts
- Select "SharedCount.com" as the count source
- Uncheck "Count Total Only" and "Hide Empty Counts"
- Select "None" as the count source
- Click "Save Changes"

Rather than using CSS to hide the count if "None" is selected, I think we should extend the current approach to exclude the count markup if "None" is selected.

Can you test the [issue/81](https://github.com/jaredatch/Shared-Counts/tree/issue/81) branch and see if it resolves the issue for you? Here's the relevant addition: https://github.com/jaredatch/Shared-Counts/commit/6d75ef1de5db62dfd3e691dd0797887a5eead2ca
