### ISSUE TITLE
Not showing any counts in the buttons.

### ISSUE THREAD

**Issue by danwilt** [jaredatch/Shared-Counts#84]
Using Shared Counts 1.3.0, no counts are showing up in the respective buttons.

## Plugin version
1.3.0

## Current Behavior
When any post, new or old is up, no shared counts appear.

## Expected Behavior
The counts should show up in each button.

## Possible Solution
Unknown fix.

## Steps to Reproduce (for bugs)
Here is an example post that has many shares (I know because we just upgraded the site using Elementor, and put in Shared Counts): https://www.danwilt.com/the-daily-examen/

<img width="835" alt="Screen Shot 2019-06-17 at 5 36 24 PM" src="https://user-images.githubusercontent.com/51933179/59641325-bc924c80-9126-11e9-850b-27e784d8617c.png">

<img width="921" alt="Screen Shot 2019-06-17 at 5 37 11 PM" src="https://user-images.githubusercontent.com/51933179/59641332-c451f100-9126-11e9-9690-89bfe3ab922c.png">

<img width="1135" alt="Screen Shot 2019-06-17 at 5 37 40 PM" src="https://user-images.githubusercontent.com/51933179/59641338-c916a500-9126-11e9-8c3b-3dc5a44f04e6.png">

<img width="1132" alt="Screen Shot 2019-06-17 at 5 37 54 PM" src="https://user-images.githubusercontent.com/51933179/59641345-cddb5900-9126-11e9-9b78-d87822c2fd24.png">

**Comment by billerickson** [comment]
Have you tried signing up for a free [SharedCount.com](https://sharedcount.com) account and using that as the source? The native option can be a bit hit or miss because Facebook throttles you based on your IP, so if you're on a shared hosting environment with other sites you might not get any count data because the other sites have already hammered Facebook.

When I paste that post URL in SharedCount it returns 174 shares. Let me know if you still get 0 shares on your site after switching over to SharedCount and I can dig into the issue further.

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2M180C2w3A0V220d1O22/Screen%20Shot%202019-09-15%20at%209.59.19%20AM.png?X-CloudApp-Visitor-Id=57dd62b2e547854fee104e672ecd4cfa&v=e531ece8)
